# Generated by Django 6.0.6 on 2026-06-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedioRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMedio', models.CharField(blank=True, max_length=255, null=True)),
                ('paraTurnado', models.IntegerField(default=0)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True, null=True)),
                ('idUsuarioRegistra', models.IntegerField(blank=True, null=True)),
                ('idUsuarioModifica', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'scs_cat_medios_recepcion',
            },
        ),
        migrations.CreateModel(
            name='PrioridadCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=10)),
                ('descripcionCriterio', models.TextField()),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True, null=True)),
                ('idUsuarioRegistra', models.IntegerField(blank=True, null=True)),
                ('idUsuarioModifica', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'scs_cat_prioridad_criterios',
            },
        ),
    ]
