# Generated by Django 6.0.6 on 2026-06-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mediorecepcion',
            table='medios',
        ),
    ]
