# Generated by Django 6.0.6 on 2026-06-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_rename_medios_recepcion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mediorecepcion',
            table='scs_cat_medios',
        ),
    ]
