# Generated by Django 6.0.6 on 2026-06-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_rename_medios_to_scs_cat_medios'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prioridadcriterio',
            table='scs_cat_prioridad',
        ),
    ]
