# Generated by Django 6.0.6 on 2026-07-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadAdministrativa',
            fields=[
                ('idUnidadAdministrativa', models.AutoField(db_column='idUnidadAdministrativa', primary_key=True, serialize=False)),
                ('clave', models.CharField(blank=True, max_length=50, null=True)),
                ('unidadAdministrativa', models.CharField(blank=True, max_length=255, null=True)),
                ('esUnidadAdministrativa', models.IntegerField(default=0)),
                ('esUnidadDeNegocio', models.IntegerField(default=0)),
                ('fechaRegistro', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaModificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('idUsuarioRegistra', models.IntegerField(blank=True, null=True)),
                ('idUsuarioModifica', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'scg_cat_unidad_administrativa',
                'ordering': ['clave'],
                'managed': False,
            },
        ),
    ]
