# Generated by Django 6.0.6 on 2026-07-27 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_crear_tabla_unidad_administrativa'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estatus',
            table='scs_cat_estatus',
        ),
        migrations.AlterModelTable(
            name='mediorecepcion',
            table='scs_cat_medios_recepcion',
        ),
        migrations.AlterModelTable(
            name='prioridadcriterio',
            table='scs_cat_criterios_prioridad',
        ),
    ]
