# Generated by Django 6.0.6 on 2026-06-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('codigo', models.CharField(max_length=10)),
                ('fechaGeneracion', models.DateTimeField(auto_now_add=True)),
                ('fechaExpiracion', models.DateTimeField()),
                ('usado', models.IntegerField(default=0)),
                ('ipSolicitante', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scs_tbl_codigos_otp',
            },
        ),
        migrations.CreateModel(
            name='CorreoAutorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('ROL1', 'Particular del Titular'), ('ROL2', 'Titular / Enlace Estratégico'), ('ADM', 'Administrador')], max_length=10)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True, null=True)),
                ('idUsuarioRegistra', models.IntegerField(blank=True, null=True)),
                ('idUsuarioModifica', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'scs_cat_correos_autorizados',
            },
        ),
    ]
