# Generated by Django 6.0.6 on 2026-06-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correoautorizado',
            name='rol',
            field=models.CharField(choices=[('ROL1', 'Particular del Titular'), ('ROL2', 'Titular / Enlace Estratégico')], max_length=10),
        ),
    ]
