# Generated by Django 6.0.6 on 2026-07-07 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_adm_to_rol1'),
        ('catalogos', '0006_unidadadministrativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoautorizado',
            name='unidadAdministrativa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos_autorizados', to='catalogos.unidadadministrativa'),
        ),
    ]
