# Generated by Django 6.0.6 on 2026-07-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_correoautorizado_unidadadministrativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correoautorizado',
            name='rol',
            field=models.CharField(choices=[('ROL1', 'Particular del Titular'), ('ROL2', 'Titular / Enlace Estratégico'), ('COMISIONADO', 'Comisionado')], max_length=15),
        ),
    ]
