# Generated by Django 6.0.6 on 2026-07-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_alter_correoautorizado_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correoautorizado',
            name='rol',
            field=models.CharField(choices=[('ROL1', 'Particular del Titular'), ('ROL2', 'Titular / Enlace Estratégico'), ('COMISIONADO', 'Comisionado'), ('EQUIPO_PARTICULAR', 'Equipo del Particular')], max_length=20),
        ),
    ]
