# Generated by Django 6.0.6 on 2026-07-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_alter_correoautorizado_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigootp',
            name='intentosFallidos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
