# Generated by Django 6.0.6 on 2026-07-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0006_codigootp_intentosfallidos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='codigootp',
            table='scs_auth_codigos_otp',
        ),
        migrations.AlterModelTable(
            name='correoautorizado',
            table='scs_auth_correos_autorizados',
        ),
    ]
