# Generated by Django 6.0.6 on 2026-08-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0009_admin_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('fechaHora', models.DateTimeField(auto_now_add=True, db_column='fecha_hora')),
            ],
            options={
                'db_table': 'scs_auth_historial_salud',
                'ordering': ['-fechaHora'],
                'indexes': [models.Index(fields=['fechaHora'], name='idx_salud_fecha')],
            },
        ),
    ]
