# Generated by Django 6.0.6 on 2026-06-19 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('fechaHora', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('contexto', models.TextField()),
                ('medioEspecificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('prioridad', models.CharField(blank=True, choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=10, null=True)),
                ('prioridadModificada', models.IntegerField(default=0)),
                ('estatusParticular', models.CharField(choices=[('Registrado', 'Registrado'), ('Turnado', 'Turnado'), ('Atendido', 'Atendido'), ('Concluido', 'Concluido')], default='Registrado', max_length=20)),
                ('fechaConclusion', models.DateTimeField(blank=True, null=True)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True, null=True)),
                ('idUsuarioRegistra', models.IntegerField(blank=True, null=True)),
                ('idUsuarioModifica', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(default=1)),
                ('idMedioRecepcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.mediorecepcion')),
                ('idSolicitanteInterno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fus_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scs_tbl_fus',
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArchivo', models.CharField(blank=True, max_length=255, null=True)),
                ('rutaArchivo', models.CharField(blank=True, max_length=500, null=True)),
                ('tipoMime', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaCarga', models.DateTimeField(auto_now_add=True, null=True)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True, null=True)),
                ('idUsuarioRegistra', models.IntegerField(blank=True, null=True)),
                ('idUsuarioModifica', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(default=1)),
                ('idFus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='solicitudes.fus')),
            ],
            options={
                'db_table': 'scs_tbl_evidencias',
            },
        ),
        migrations.CreateModel(
            name='SolicitanteExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True, null=True)),
                ('idUsuarioRegistra', models.IntegerField(blank=True, null=True)),
                ('idUsuarioModifica', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(default=1)),
                ('idFus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitante_externo', to='solicitudes.fus')),
            ],
            options={
                'db_table': 'scs_tbl_solicitantes_externos',
            },
        ),
        migrations.CreateModel(
            name='Turnado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitudTexto', models.TextField(blank=True, null=True)),
                ('fechaHoraTurnado', models.DateTimeField(blank=True, null=True)),
                ('estatusTitular', models.CharField(choices=[('Recibido', 'Recibido'), ('En_seguimiento', 'En seguimiento'), ('Concluido', 'Concluido')], default='Recibido', max_length=20)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True, null=True)),
                ('idUsuarioRegistra', models.IntegerField(blank=True, null=True)),
                ('idUsuarioModifica', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(default=1)),
                ('idDestinatario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnados_recibidos', to=settings.AUTH_USER_MODEL)),
                ('idFus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnados', to='solicitudes.fus')),
                ('idMedio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.mediorecepcion')),
                ('idRemitente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnados_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scs_tbl_turnados',
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaActividad', models.DateField(blank=True, null=True)),
                ('descripcionActividad', models.TextField()),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True, null=True)),
                ('idUsuarioRegistra', models.IntegerField(blank=True, null=True)),
                ('idUsuarioModifica', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(default=1)),
                ('idTurnado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='solicitudes.turnado')),
            ],
            options={
                'db_table': 'scs_tbl_seguimientos',
            },
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroOrden', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('completada', models.IntegerField(default=0)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True, null=True)),
                ('idUsuarioRegistra', models.IntegerField(blank=True, null=True)),
                ('idUsuarioModifica', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(default=1)),
                ('idTurnado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='solicitudes.turnado')),
            ],
            options={
                'db_table': 'scs_tbl_acciones',
            },
        ),
    ]
