# Generated by Django 6.0.6 on 2026-06-22 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fusFolio', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaHora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=50)),
                ('accion', models.CharField(choices=[('REGISTRO_FUS', 'Registro FUS'), ('TURNAR_FUS', 'Turnar FUS'), ('ASIGNACION_ESTADO', 'Asignación automática de estado'), ('REGISTRO_RESPUESTA', 'Registro de respuesta/seguimiento'), ('REGISTRO_ACCION', 'Registro de acción por emprender'), ('CONCLUSION_FUS', 'Conclusión FUS'), ('REAPERTURA_FUS', 'Reapertura FUS'), ('INICIO_SESION', 'Inicio de sesión'), ('CIERRE_SESION', 'Cierre de sesión'), ('ELIMINACION', 'Eliminación lógica')], max_length=30)),
                ('estadoAnterior', models.CharField(blank=True, max_length=50, null=True)),
                ('estadoNuevo', models.CharField(blank=True, max_length=50, null=True)),
                ('ipCliente', models.GenericIPAddressField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scs_tbl_bitacora',
            },
        ),
        migrations.AddField(
            model_name='evidencia',
            name='hashSha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fusFolio', models.CharField(max_length=100)),
                ('tipoEvento', models.CharField(choices=[('TURNADO', 'FUS Turnado'), ('RESPUESTA', 'Nueva respuesta'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('CONCLUIDO', 'FUS Concluido')], max_length=20)),
                ('mensaje', models.TextField()),
                ('fechaGeneracion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.IntegerField(default=0)),
                ('fechaLectura', models.DateTimeField(blank=True, null=True)),
                ('idDestinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scs_tbl_notificaciones',
            },
        ),
    ]
