# Generated by Django 6.0.6 on 2026-06-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_bitacora_evidencia_hashsha256_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='accionTexto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
