# Generated by Django 6.0.6 on 2026-06-29 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('solicitudes', '0004_fus_fechalimite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fus',
            name='fechaLimite',
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['usuario'], name='idx_bitacora_usuario'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['fusFolio'], name='idx_bitacora_folio'),
        ),
        migrations.AddIndex(
            model_name='bitacora',
            index=models.Index(fields=['fechaHora'], name='idx_bitacora_fecha'),
        ),
        migrations.AddIndex(
            model_name='fus',
            index=models.Index(fields=['estatusParticular'], name='idx_fus_estatus'),
        ),
        migrations.AddIndex(
            model_name='fus',
            index=models.Index(fields=['folio'], name='idx_fus_folio'),
        ),
        migrations.AddIndex(
            model_name='fus',
            index=models.Index(fields=['fechaRegistro'], name='idx_fus_fecha'),
        ),
        migrations.AddIndex(
            model_name='fus',
            index=models.Index(fields=['idSolicitanteInterno'], name='idx_fus_solicitante'),
        ),
        migrations.AddIndex(
            model_name='turnado',
            index=models.Index(fields=['idDestinatario'], name='idx_turnado_dest'),
        ),
        migrations.AddIndex(
            model_name='turnado',
            index=models.Index(fields=['estatusTitular'], name='idx_turnado_estatus'),
        ),
    ]
