# Generated by Django 6.0.6 on 2026-06-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_fus_remove_fechalimite'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seguimiento',
            table='scs_tbl_respuestas',
        ),
    ]
