# Generated by Django 6.0.6 on 2026-06-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_rename_seguimientos_to_respuestas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accion',
        ),
    ]
