# Generated by Django 6.0.6 on 2026-06-30 17:20

from django.db import migrations, models


def copiar_datos_solicitante(apps, schema_editor):
    FUS = apps.get_model('solicitudes', 'FUS')
    SolicitanteExterno = apps.get_model('solicitudes', 'SolicitanteExterno')
    for s in SolicitanteExterno.objects.all():
        FUS.objects.filter(pk=s.idFus_id).update(
            nombreExterno=s.nombre,
            telefonoExterno=s.telefono,
            correoExterno=s.correo,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_delete_accion_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='fus',
            name='correoExterno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fus',
            name='nombreExterno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fus',
            name='telefonoExterno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(copiar_datos_solicitante, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='SolicitanteExterno',
        ),
    ]
