# Generated by Django 6.0.6 on 2026-07-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_alter_bitacora_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
