# Generated by Django 6.0.6 on 2026-07-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0011_evidencia_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='fus',
            name='criterios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
