# Generated by Django 6.0.6 on 2026-07-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0012_fus_criterios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguimiento',
            options={'ordering': ['fechaRegistro']},
        ),
    ]
