# Generated by Django 6.0.6 on 2026-07-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0013_alter_seguimiento_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fus',
            name='fechaLimite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipoEvento',
            field=models.CharField(choices=[('TURNADO', 'FUS Turnado'), ('RESPUESTA', 'Nueva respuesta'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('CONCLUIDO', 'FUS Concluido'), ('SLA_POR_VENCER', 'SLA por vencer')], max_length=20),
        ),
    ]
