# Generated by Django 6.0.6 on 2026-07-14 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0014_fus_fechalimite_alter_notificacion_tipoevento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipoEvento',
            field=models.CharField(choices=[('TURNADO', 'FUS Turnado'), ('RESPUESTA', 'Nueva respuesta'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('CONCLUIDO', 'FUS Concluido'), ('SLA_POR_VENCER', 'SLA por vencer'), ('ACTIVIDAD', 'Actividad de calendario')], max_length=20),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('reunion', 'Reunión'), ('fus', 'FUS vinculado'), ('limite', 'Fecha límite'), ('institucional', 'Institucional')], default='reunion', max_length=20)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.SmallIntegerField(default=1)),
                ('idCreador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL)),
                ('idFusRelacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solicitudes.fus')),
                ('participantes', models.ManyToManyField(blank=True, related_name='actividades_invitado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scs_tbl_actividades',
            },
        ),
    ]
