# Generated by Django 6.0.6 on 2026-07-17 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0015_alter_notificacion_tipoevento_actividad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fus',
            name='fechaAsignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fus',
            name='idComisionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fus_comisionados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('REGISTRO_FUS', 'Registro FUS'), ('TURNAR_FUS', 'Turnar FUS'), ('ASIGNACION_ESTADO', 'Asignación automática de estado'), ('REGISTRO_RESPUESTA', 'Registro de respuesta/seguimiento'), ('REGISTRO_ACCION', 'Registro de acción por emprender'), ('CONCLUSION_FUS', 'Conclusión FUS'), ('REAPERTURA_FUS', 'Reapertura FUS'), ('INICIO_SESION', 'Inicio de sesión'), ('CIERRE_SESION', 'Cierre de sesión'), ('RESTABLECER_CONTRASENA', 'Restablecimiento de contraseña'), ('ELIMINACION', 'Eliminación lógica'), ('ASIGNACION_COMISIONADO', 'Asignación a comisionado'), ('SEGUIMIENTO_COMISIONADO', 'Seguimiento de comisionado'), ('FINALIZACION_SEGUIMIENTO', 'Finalización de seguimiento'), ('APROBACION_FUS', 'Aprobación de FUS'), ('RECHAZO_FUS', 'Rechazo de FUS')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipoEvento',
            field=models.CharField(choices=[('TURNADO', 'FUS Turnado'), ('RESPUESTA', 'Nueva respuesta'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('CONCLUIDO', 'FUS Concluido'), ('SLA_POR_VENCER', 'SLA por vencer'), ('ACTIVIDAD', 'Actividad de calendario'), ('ASIGNADO_COMISIONADO', 'FUS asignado a comisionado'), ('SEGUIMIENTO_FINALIZADO', 'Seguimiento finalizado'), ('SOLICITUD_APROBADA', 'Solicitud aprobada'), ('SOLICITUD_RECHAZADA', 'Solicitud rechazada')], max_length=25),
        ),
        migrations.CreateModel(
            name='SeguimientoRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('accion_por_emprender', 'Acción por emprender'), ('avance', 'Avance'), ('finalizacion', 'Finalización'), ('rechazo', 'Rechazo')], max_length=25)),
                ('contenido', models.TextField()),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.SmallIntegerField(default=1)),
                ('idAutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_comisionado', to=settings.AUTH_USER_MODEL)),
                ('idFus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientosComisionado', to='solicitudes.fus')),
            ],
            options={
                'db_table': 'scs_tbl_seguimiento_comisionado',
                'ordering': ['fechaRegistro'],
            },
        ),
    ]
