# Generated by Django 6.0.6 on 2026-07-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0016_fus_fechaasignacion_fus_idcomisionado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('REGISTRO_FUS', 'Registro FUS'), ('TURNAR_FUS', 'Turnar FUS'), ('ASIGNACION_ESTADO', 'Asignación automática de estado'), ('REGISTRO_RESPUESTA', 'Registro de respuesta/seguimiento'), ('REGISTRO_ACCION', 'Registro de acción por emprender'), ('CONCLUSION_FUS', 'Conclusión FUS'), ('REAPERTURA_FUS', 'Reapertura FUS'), ('INICIO_SESION', 'Inicio de sesión'), ('CIERRE_SESION', 'Cierre de sesión'), ('RESTABLECER_CONTRASENA', 'Restablecimiento de contraseña'), ('ELIMINACION', 'Eliminación lógica'), ('ASIGNACION_COMISIONADO', 'Asignación a comisionado'), ('SEGUIMIENTO_COMISIONADO', 'Seguimiento de comisionado'), ('FINALIZACION_SEGUIMIENTO', 'Finalización de seguimiento'), ('ATENCION_FUS', 'Atención de FUS (comisionado)'), ('APROBACION_FUS', 'Aprobación de FUS'), ('RECHAZO_FUS', 'Rechazo de FUS')], max_length=30),
        ),
    ]
