# Generated by Django 6.0.6 on 2026-07-27 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_renombrar_tablas_catalogos'),
        ('solicitudes', '0017_atencion_fus_accion_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fus',
            name='correoExterno',
            field=models.CharField(blank=True, db_column='solicitante_externo_correo', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fus',
            name='estatusParticular',
            field=models.ForeignKey(db_column='estatus_particular', default='Registrado', on_delete=django.db.models.deletion.PROTECT, related_name='fus_set', to='catalogos.estatus', to_field='clave'),
        ),
        migrations.AlterField(
            model_name='fus',
            name='fechaAsignacion',
            field=models.DateTimeField(blank=True, db_column='fecha_asignacion', null=True),
        ),
        migrations.AlterField(
            model_name='fus',
            name='fechaConclusion',
            field=models.DateTimeField(blank=True, db_column='fecha_conclusion', null=True),
        ),
        migrations.AlterField(
            model_name='fus',
            name='fechaHora',
            field=models.DateTimeField(blank=True, db_column='fecha_hora', null=True),
        ),
        migrations.AlterField(
            model_name='fus',
            name='fechaLimite',
            field=models.DateTimeField(blank=True, db_column='fecha_limite', null=True),
        ),
        migrations.AlterField(
            model_name='fus',
            name='fechaModificacion',
            field=models.DateTimeField(auto_now=True, db_column='fecha_modificacion', null=True),
        ),
        migrations.AlterField(
            model_name='fus',
            name='fechaRegistro',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_registro', null=True),
        ),
        migrations.AlterField(
            model_name='fus',
            name='idComisionado',
            field=models.ForeignKey(blank=True, db_column='comisionado_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fus_comisionados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fus',
            name='idMedioRecepcion',
            field=models.ForeignKey(db_column='medio_recepcion_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.mediorecepcion'),
        ),
        migrations.AlterField(
            model_name='fus',
            name='idSolicitanteInterno',
            field=models.ForeignKey(db_column='solicitante_interno_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fus_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fus',
            name='idUsuarioModifica',
            field=models.IntegerField(blank=True, db_column='usuario_modifica_id', null=True),
        ),
        migrations.AlterField(
            model_name='fus',
            name='idUsuarioRegistra',
            field=models.IntegerField(blank=True, db_column='usuario_registra_id', null=True),
        ),
        migrations.AlterField(
            model_name='fus',
            name='medioEspecificacion',
            field=models.CharField(blank=True, db_column='medio_especificacion', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fus',
            name='nombreExterno',
            field=models.CharField(blank=True, db_column='solicitante_externo_nombre', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fus',
            name='prioridadModificada',
            field=models.IntegerField(db_column='prioridad_modificada', default=0),
        ),
        migrations.AlterField(
            model_name='fus',
            name='telefonoExterno',
            field=models.CharField(blank=True, db_column='solicitante_externo_telefono', max_length=20, null=True),
        ),
    ]
