# Generated by Django 6.0.6 on 2026-07-27 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0018_renombrar_columnas_fus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='fechaCarga',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_carga', null=True),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='fechaModificacion',
            field=models.DateTimeField(auto_now=True, db_column='fecha_modificacion', null=True),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='fechaRegistro',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_registro', null=True),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='hashSha256',
            field=models.CharField(blank=True, db_column='hash_sha256', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='idFus',
            field=models.ForeignKey(db_column='fus_id', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='solicitudes.fus'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='idUsuarioModifica',
            field=models.IntegerField(blank=True, db_column='usuario_modifica_id', null=True),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='idUsuarioRegistra',
            field=models.IntegerField(blank=True, db_column='usuario_registra_id', null=True),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='nombreArchivo',
            field=models.CharField(blank=True, db_column='nombre_archivo', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='rutaArchivo',
            field=models.CharField(blank=True, db_column='ruta_archivo', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='tipoMime',
            field=models.CharField(blank=True, db_column='tipo_mime', max_length=100, null=True),
        ),
    ]
