# Generated by Django 6.0.6 on 2026-07-27 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_renombrar_tablas_catalogos'),
        ('solicitudes', '0019_renombrar_columnas_evidencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnado',
            name='estatusTitular',
            field=models.ForeignKey(db_column='estatus_titular', default='Recibido', on_delete=django.db.models.deletion.PROTECT, related_name='turnados_set', to='catalogos.estatus', to_field='clave'),
        ),
        migrations.AlterField(
            model_name='turnado',
            name='fechaHoraTurnado',
            field=models.DateTimeField(blank=True, db_column='fecha_hora_turnado', null=True),
        ),
        migrations.AlterField(
            model_name='turnado',
            name='fechaModificacion',
            field=models.DateTimeField(auto_now=True, db_column='fecha_modificacion', null=True),
        ),
        migrations.AlterField(
            model_name='turnado',
            name='fechaRegistro',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_registro', null=True),
        ),
        migrations.AlterField(
            model_name='turnado',
            name='idDestinatario',
            field=models.ForeignKey(db_column='destinatario_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnados_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turnado',
            name='idFus',
            field=models.ForeignKey(db_column='fus_id', on_delete=django.db.models.deletion.CASCADE, related_name='turnados', to='solicitudes.fus'),
        ),
        migrations.AlterField(
            model_name='turnado',
            name='idMedio',
            field=models.ForeignKey(db_column='medio_recepcion_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.mediorecepcion'),
        ),
        migrations.AlterField(
            model_name='turnado',
            name='idRemitente',
            field=models.ForeignKey(db_column='remitente_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnados_enviados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turnado',
            name='idUsuarioModifica',
            field=models.IntegerField(blank=True, db_column='usuario_modifica_id', null=True),
        ),
        migrations.AlterField(
            model_name='turnado',
            name='idUsuarioRegistra',
            field=models.IntegerField(blank=True, db_column='usuario_registra_id', null=True),
        ),
        migrations.AlterField(
            model_name='turnado',
            name='solicitudTexto',
            field=models.TextField(blank=True, db_column='solicitud_texto', null=True),
        ),
    ]
