# Generated by Django 6.0.6 on 2026-07-27 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0020_renombrar_columnas_turnado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='accionTexto',
            field=models.CharField(blank=True, db_column='accion_texto', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='descripcionActividad',
            field=models.TextField(db_column='descripcion_actividad'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fechaActividad',
            field=models.DateField(blank=True, db_column='fecha_actividad', null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fechaModificacion',
            field=models.DateTimeField(auto_now=True, db_column='fecha_modificacion', null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fechaRegistro',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_registro', null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='idTurnado',
            field=models.ForeignKey(db_column='turnado_id', on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='solicitudes.turnado'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='idUsuarioModifica',
            field=models.IntegerField(blank=True, db_column='usuario_modifica_id', null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='idUsuarioRegistra',
            field=models.IntegerField(blank=True, db_column='usuario_registra_id', null=True),
        ),
    ]
