# Generated by Django 6.0.6 on 2026-07-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0021_renombrar_columnas_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='estadoAnterior',
            field=models.CharField(blank=True, db_column='estado_anterior', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='estadoNuevo',
            field=models.CharField(blank=True, db_column='estado_nuevo', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='fechaHora',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_hora'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='fusFolio',
            field=models.CharField(blank=True, db_column='fus_folio', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='ipCliente',
            field=models.GenericIPAddressField(blank=True, db_column='ip_cliente', null=True),
        ),
    ]
