# Generated by Django 6.0.6 on 2026-07-27 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0022_renombrar_columnas_bitacora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fechaGeneracion',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_generacion'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fechaLectura',
            field=models.DateTimeField(blank=True, db_column='fecha_lectura', null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fusFolio',
            field=models.CharField(db_column='fus_folio', max_length=100),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='idDestinatario',
            field=models.ForeignKey(db_column='destinatario_id', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipoEvento',
            field=models.CharField(choices=[('TURNADO', 'FUS Turnado'), ('RESPUESTA', 'Nueva respuesta'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('CONCLUIDO', 'FUS Concluido'), ('SLA_POR_VENCER', 'SLA por vencer'), ('ACTIVIDAD', 'Actividad de calendario'), ('ASIGNADO_COMISIONADO', 'FUS asignado a comisionado'), ('SEGUIMIENTO_FINALIZADO', 'Seguimiento finalizado'), ('SOLICITUD_APROBADA', 'Solicitud aprobada'), ('SOLICITUD_RECHAZADA', 'Solicitud rechazada')], db_column='tipo_evento', max_length=25),
        ),
    ]
