# Generated by Django 6.0.6 on 2026-07-27 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0023_renombrar_columnas_notificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_creacion'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='horaFin',
            field=models.TimeField(db_column='hora_fin'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='horaInicio',
            field=models.TimeField(db_column='hora_inicio'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='idCreador',
            field=models.ForeignKey(db_column='creador_id', on_delete=django.db.models.deletion.CASCADE, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='idFusRelacionado',
            field=models.ForeignKey(blank=True, db_column='fus_relacionado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='solicitudes.fus'),
        ),
    ]
