# Generated by Django 6.0.6 on 2026-07-27 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0024_renombrar_columnas_actividad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientorespuesta',
            name='fechaRegistro',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_registro'),
        ),
        migrations.AlterField(
            model_name='seguimientorespuesta',
            name='idAutor',
            field=models.ForeignKey(db_column='autor_id', on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_comisionado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seguimientorespuesta',
            name='idFus',
            field=models.ForeignKey(db_column='fus_id', on_delete=django.db.models.deletion.CASCADE, related_name='seguimientosComisionado', to='solicitudes.fus'),
        ),
    ]
