# Generated by Django 6.0.6 on 2026-07-29 18:33

import os

from django.conf import settings
from django.db import migrations, models


def backfill_tamano_bytes(apps, schema_editor):
    """Evidencias subidas antes de este campo no tienen tamaño registrado —
    se completa leyendo el archivo real en MEDIA_ROOT (best-effort: si ya no
    existe en disco, se deja en NULL en vez de fallar la migración)."""
    Evidencia = apps.get_model('solicitudes', 'Evidencia')
    for ev in Evidencia.objects.filter(tamanoBytes__isnull=True, activo=1).exclude(rutaArchivo__isnull=True):
        ruta = os.path.join(settings.MEDIA_ROOT, ev.rutaArchivo)
        try:
            ev.tamanoBytes = os.path.getsize(ruta)
            ev.save(update_fields=['tamanoBytes'])
        except OSError:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0026_renombrar_relacion_actividad_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='tamanoBytes',
            field=models.PositiveIntegerField(blank=True, db_column='tamano_bytes', null=True),
        ),
        migrations.RunPython(backfill_tamano_bytes, migrations.RunPython.noop),
    ]
