# Generated by Django 6.0.6 on 2026-08-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0030_alter_fus_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fus',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=10, null=True),
        ),
    ]
