# Generated by Django 6.0.6 on 2026-08-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0031_alter_fus_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnado',
            name='medioEspecificacion',
            field=models.CharField(blank=True, db_column='medio_especificacion', max_length=255, null=True),
        ),
    ]
