# Generated by Django 6.0.6 on 2026-08-14 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0033_fulltext_busqueda_fus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['fecha'], name='idx_actividad_fecha'),
        ),
    ]
