# Generated by Django 6.0.6 on 2026-08-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0035_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientorespuesta',
            name='accionTexto',
            field=models.CharField(blank=True, db_column='accion_texto', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seguimientorespuesta',
            name='fechaActividad',
            field=models.DateField(blank=True, db_column='fecha_actividad', null=True),
        ),
    ]
