MODULOS = (
    'INICIO',
    'CALENDARIO',
    'CONSULTAR_FUS',
    'REGISTRAR_FUS',
    'SOLICITUDES_TURNADAS',
    'BUSQUEDA_AVANZADA',
    'REPORTES',
    'USUARIOS_ACCESOS',
    'AUTENTICACION',
    'BITACORA',
    'SOLICITUDES_ASIGNADAS',
    'ADMIN_RESUMEN',
    'ADMIN_USUARIOS',
    'ADMIN_SALUD',
    'ADMIN_AUDITORIA',
    'ADMIN_OTP',
    'ADMIN_USO',
    'ACCESO',
    'DESCONOCIDO',
)

TAXONOMIA_VERSION = '1.0'

EVENTOS = (
    'PAGE_VIEW',
    'INTERACTION',
    'FORM_STARTED',
    'FORM_SUBMITTED',
    'FORM_ABANDONED',
    'TASK_STARTED',
    'TASK_COMPLETED',
    'TASK_FAILED',
    'TASK_ABANDONED',
)

ACCIONES = ('SEARCH', 'FILTER', 'EXPORT', 'OPEN', 'CREATE', 'UPDATE', 'NAVIGATE')

EVENTOS_SIGNIFICATIVOS = frozenset(EVENTOS) - {'PAGE_VIEW'}

EVENTOS_TERMINALES = frozenset({
    'FORM_SUBMITTED', 'FORM_ABANDONED',
    'TASK_COMPLETED', 'TASK_FAILED', 'TASK_ABANDONED',
})

EMBUDOS = (
    ('FORMULARIO', ('FORM_STARTED', 'FORM_SUBMITTED', 'FORM_ABANDONED')),
    ('TAREA', ('TASK_STARTED', 'TASK_COMPLETED', 'TASK_FAILED', 'TASK_ABANDONED')),
)
